### ISSUE TITLE
Feature Request: Support AMD Modules

### ISSUE THREAD

**Issue by MaxMem** [hughsk/colony#1]
Visualizing modules conforming to Asynchronous Module Definition (server or client side) would be a great addition.

**Comment by hughsk** [comment]
I'm not a big fan of AMD, but this could come from the fact I'm not very familiar with it either. 

That being said, if someone submitted a pull request with the changes I'd happily merge it - this is better off done in [reqursive](/hughsk/reqursive) though, which colony uses for resolving the modules. So I've opened an issue there as well :)
