### ISSUE TITLE
json flag causes empty output

### ISSUE THREAD

**Issue by juliangruber** [hughsk/colony#4]
``` bash
$ colony --npm browserify
```

creates a folder as it should,

``` bash
$ colony --npm browserify --json
```

just outputs

```
{"nodes":[],"links":[],"scale":1}
```

without even reaching out to npm.

**Comment by hughsk** [comment]
Ah weird, I'll have a look at this over the weekend - there's a couple of things I've been meaning to improve for a while now. Thanks!

**Comment by hughsk** [comment]
Sorry it took so long to get around to this - but fixed as of 0.0.6 :)

**Comment by derekakers** [comment]
nice groove.  what do you like about it?

-------- Original Message --------
Subject: Re: [colony] json flag causes empty output (#4)

**Comment by juliangruber** [comment]
:dancer:
