### ISSUE TITLE
plugin an arbitrary dependency graph?

### ISSUE THREAD

**Issue by jonathanong** [hughsk/colony#7]
i'm not too familiar with d3 and stuff. is it possible to just plug in my own dependency graph and such? essentially, i want to make a file-based dependency graph using this: https://github.com/normalize/walker.js 

if it's too difficult to abstract then it's cool. i'm sure i can figure it out somehow.

**Comment by hughsk** [comment]
Hey @jonathanong, unfortunately colony isn't too generic – I'm not sure how easy it would be to plug into, though you're welcome to try :)

That being said, once you can get your data into d3's [hierarchy layout](https://github.com/mbostock/d3/wiki/Hierarchy-Layout) format it should be pretty straightforward to  write something similar! Here's a simple example: http://bl.ocks.org/mbostock/4062045

**Comment by jonathanong** [comment]
hmm ok. i guess i'll learn d3 sooner or later.

side note though: shit keeps getting smaller as i click on them. what's up with that?

**Comment by hughsk** [comment]
Haha, how do you mean?
